name: Benchmark

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  site-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      WORKING_DIR: benchmark
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

      - name: Install resvg to path
        run: |
          mkdir -p /tmp/resvg
          cd /tmp/resvg
          echo /tmp/resvg >> $GITHUB_PATH
          curl -s https://api.github.com/repos/RazrFalcon/resvg/releases/latest | jq -r '.assets[] | select(.name | contains("resvg-linux")) | .browser_download_url' | head -n1 | xargs curl -O -L
          tar -zxvf resvg-linux-x86_64.tar.gz
          ./resvg --help
          cd -

      - run: pnpm start
        working-directory: ${{ env.WORKING_DIR }}

      - name: Push benchmark result
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          BRANCH_NAME=benchmark-$(date +"%Y%m%d-%H%M%S")
          git switch -c $BRANCH_NAME
          git add .
          git commit -m "chore: update $BRANCH_NAME"
          git push -u origin $BRANCH_NAME
