name: Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: npm version ?
        required: true
        default: patch

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup git
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Version up
        id: version
        run: |
          CURRENT_TAG=$(npm version ${{ github.event.inputs.version }})
          echo "CURRENT_TAG: $CURRENT_TAG"
          echo ::set-output name=CURRENT_TAG::$CURRENT_TAG
      - run: |
          git push origin
          git push origin --tags
    outputs:
      version: ${{ steps.version.outputs.CURRENT_TAG }}

  release:
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.7
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: pnpm
      - name: WASM target
        run: rustup target add wasm32-unknown-unknown
      - name: Install deps
        run: pnpm install

      - name: Cache build files
        uses: actions/cache@v2
        env:
          cache-name: cache-build-files
        with:
          path: |
            pkg-umd
            pkg-node
            umd
            cjs
            esm
            target
          key: ${{ env.cache-name }}-${{ github.sha }}
      - name: Build
        run: pnpm make

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ needs.version.outputs.CURRENT_TAG }}
          files: cjs/svg2png_wasm_bg.wasm
